import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Link from "next/link";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      >
       <Navbar />
        {children}
        <footer className="bg-neutral-900 text-white py-6 sm:px-8 px-6">
          <div className="max-w-screen-xl mx-auto flex items-center justify-between">
                <div className={"ui-nav-title"}>
                    <Link href="/"><h1 translate="no">Rōnin Robotics</h1></Link>
                </div>
                <div className="">&copy; 2025 Rōnin Robotics</div>
            </div>
        </footer>
      </body>
    </html>
  );
}
